Feature/rkm66 68 nav bar
isd-sgcu/rpkm66-frontend pull request #72
Opened 2023-07-28 10:06 UTC by PwFaze

## Change made

-   [ ] Bug fixes
-   [ ] New features
-   [ ] Breaking changes

## Describe what you have done

-

### New Features

-

### Fix

-

### Others

-

2023-07-28 16:08 UTC, shalluv requested changes

2023-07-28 16:08 UTC, shalluv commented on src/pages/profile.tsx
> +const Test = () => {
Please rename this.

2023-07-28 16:08 UTC, shalluv commented on src/components/PhaseTwoNavbar.tsx
> +                                : 'hover:text-amber-400'
The code `hover:text-amber-400` already exists, so when `router.pathname != '/article-page'`, it has no effect. You can remove it if I am correct.

2023-07-28 16:08 UTC, shalluv commented on src/components/PhaseTwoNavbar.tsx
> +                                : 'hover:text-amber-400'
Same as above.

2023-07-28 16:08 UTC, shalluv commented on src/components/PhaseTwoNavbar.tsx
> +                                : 'hover:text-amber-400'
Same as above.

2023-07-28 16:08 UTC, shalluv commented on src/components/PhaseTwoNavbar.tsx
> +        <nav className="sticky top-0 z-40 flex h-11 w-full justify-between bg-black/50 px-2 py-2 backdrop-blur-sm md:px-5 lg:h-20 lg:px-10 lg:py-4">
Instead of using `px-2` and `py-2`, you can simply use `p-2`.

2023-07-29 13:52 UTC, boomchanotai requested changes
Super cool!

2023-07-29 13:52 UTC, boomchanotai commented on src/components/PhaseTwoNavbar.tsx
> +                    <BellIcon
Does it have this button on design?

2023-07-29 14:10 UTC, isd-team-sgcu approved these changes
Well Done !

2023-07-29 14:11 UTC, boomchanotai approved these changes
LGTM!

2023-07-29 14:19 UTC, shalluv approved these changes
Boom told me to approve, and I trust Boom with my life 😘

2023-07-29 14:20 UTC, merged