feat: scan qr
isd-sgcu/rpkm66-frontend pull request #73
Opened 2023-07-28 15:45 UTC by Suprawich

## Change made

-   [ ] Bug fixes
-   [ / ] New features
-   [ ] Breaking changes

## Describe what you have done

-

### New Features

-

### Fix

-

### Others

-

2023-07-28 16:32 UTC, shalluv requested changes

2023-07-28 16:32 UTC, shalluv commented on src/pages/scan.tsx
> +                            <a
Please use `Link` from `Next.JS`.

2023-07-28 16:32 UTC, shalluv commented on src/pages/scan.tsx
> +                </div>
Change this `div` element to a `button` element and remove the nested button. The current implementation is overly complicated.

2023-07-29 14:24 UTC, shalluv approved these changes, later dismissed
I approve the work for the sake of passing it on to Boom, so this PR will not be blocked by my requested changes. However, please make the requested changes.

2023-07-29 16:29 UTC, Suprawich commented
@boomchanotai แก้ให้แล้วครับฝากดูให้ทีครับ

2023-07-29 16:39 UTC, boomchanotai approved these changes, later dismissed
Great Job!

2023-07-29 16:39 UTC, boomchanotai commented on src/pages/scan.tsx
> +            <div className="inset-0 flex w-full items-center justify-center bg-black">
`inset-0` do nothing 

It should be use with `postition: absolute or fixed`

2023-07-29 18:02 UTC, Suprawich commented on src/pages/scan.tsx
> +            <div className="inset-0 flex w-full items-center justify-center bg-black">
ลบ inset-0 ไปแล้วครับ แต่ตรง vercel ข้างล่างต้องแก้ยังไงหรอครับ

2023-07-30 03:09 UTC, boomchanotai approved these changes
Great Job ! เมื่อคืนหา type ของ lib ตัวนี้อยู่เหมือนกัน แต่สรุป any ไปเหอะ มันไม่มี type ให้ 5555

2023-07-30 03:09 UTC, merged